// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.
package org.sapia.ubik.rmi.examples;

public final class JdkFoo_Stub extends java.rmi.server.RemoteStub
  implements org.sapia.ubik.rmi.examples.Foo, java.rmi.Remote {
  private static final long               serialVersionUID = 2;
  private static java.lang.reflect.Method $method_getBar_0;

  static {
    try {
      $method_getBar_0 = org.sapia.ubik.rmi.examples.Foo.class.getMethod("getBar",
          new java.lang.Class[] {  });
    } catch (java.lang.NoSuchMethodException e) {
      throw new java.lang.NoSuchMethodError("stub class initialization failed");
    }
  }

  // constructors
  public JdkFoo_Stub(java.rmi.server.RemoteRef ref) {
    super(ref);
  }

  // methods from remote interfaces
  // implementation of getBar()
  public org.sapia.ubik.rmi.examples.Bar getBar()
    throws java.rmi.RemoteException {
    try {
      Object $result = ref.invoke(this, $method_getBar_0, null,
          -3009707282837911082L);

      return ((org.sapia.ubik.rmi.examples.Bar) $result);
    } catch (java.lang.RuntimeException e) {
      throw e;
    } catch (java.rmi.RemoteException e) {
      throw e;
    } catch (java.lang.Exception e) {
      throw new java.rmi.UnexpectedException("undeclared checked exception", e);
    }
  }
}
