// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.
package org.sapia.ubik.rmi.examples;

public final class JdkBar_Stub extends java.rmi.server.RemoteStub
  implements org.sapia.ubik.rmi.examples.Bar, java.rmi.Remote {
  private static final long               serialVersionUID = 2;
  private static java.lang.reflect.Method $method_getMsg_0;

  static {
    try {
      $method_getMsg_0 = org.sapia.ubik.rmi.examples.Bar.class.getMethod("getMsg",
          new java.lang.Class[] {  });
    } catch (java.lang.NoSuchMethodException e) {
      throw new java.lang.NoSuchMethodError("stub class initialization failed");
    }
  }

  // constructors
  public JdkBar_Stub(java.rmi.server.RemoteRef ref) {
    super(ref);
  }

  // methods from remote interfaces
  // implementation of getMsg()
  public java.lang.String getMsg() throws java.rmi.RemoteException {
    try {
      Object $result = ref.invoke(this, $method_getMsg_0, null,
          489183614250787710L);

      return ((java.lang.String) $result);
    } catch (java.lang.RuntimeException e) {
      throw e;
    } catch (java.rmi.RemoteException e) {
      throw e;
    } catch (java.lang.Exception e) {
      throw new java.rmi.UnexpectedException("undeclared checked exception", e);
    }
  }
}
